# Generated by Django 2.2.6 on 2019-10-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrimPay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='plan_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
