# Generated by Django 2.2.6 on 2019-10-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrimPay', '0002_auto_20191004_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='plan_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
