# Generated by Django 2.2.6 on 2019-10-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrimPay', '0003_auto_20191004_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
