# Generated by Django 2.2.6 on 2019-10-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScrimPay', '0004_service_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='main',
            unique_together={('user_id', 'service_id')},
        ),
    ]
